name: Build Multi-Platform Executable

on:
  push:
    tags: ['v*']  # 在推送标签时触发构建
  workflow_dispatch:  # 允许手动触发

env:
  APP_NAME: "YourAppName"  # 替换为您的应用名称

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']
        architecture: ['x64']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyside6 python-socketio requests

    - name: Build Windows executable
      run: |
        python -m nuitka ^
          --standalone ^
          --onefile ^
          --enable-plugin=pyside6 ^
          --include-qt-plugins=all ^
          --include-package=socketio ^
          --include-package=engineio ^
          --include-package=requests ^
          --include-package=urllib3 ^
          --include-package=charset_normalizer ^
          --include-package=idna ^
          --windows-icon-from-ico=assets/icon.ico ^
          --windows-console-mode=disable ^
          --remove-output ^
          --noinclude-pytest-mode=nofollow ^
          --noinclude-unittest-mode=nofollow ^
          --nofollow-imports ^
          --follow-stdlib ^
          --lto=yes ^
          --jobs=4 ^
          --windows-company-name="Your Company" ^
          --windows-product-name="${{ env.APP_NAME }}" ^
          --windows-file-version="1.0.0" ^
          --windows-product-version="1.0.0" ^
          --windows-file-description="PySide6 and Socket.IO Application" ^
          --output-filename=${{ env.APP_NAME }}-windows-${{ matrix.python-version }}-${{ matrix.architecture }}.exe ^
          app.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: ${{ env.APP_NAME }}-windows-${{ matrix.python-version }}-${{ matrix.architecture }}.exe

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y patchelf

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyside6 python-socketio requests

    - name: Build Linux executable
      run: |
        python -m nuitka \
          --standalone \
          --onefile \
          --enable-plugin=pyside6 \
          --include-qt-plugins=all \
          --include-package=socketio \
          --include-package=engineio \
          --include-package=requests \
          --include-package=urllib3 \
          --include-package=charset_normalizer \
          --include-package=idna \
          --remove-output \
          --noinclude-pytest-mode=nofollow \
          --noinclude-unittest-mode=nofollow \
          --nofollow-imports \
          --follow-stdlib \
          --lto=yes \
          --jobs=4 \
          --output-filename=${{ env.APP_NAME }}-linux-${{ matrix.python-version }} \
          app.py

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: ${{ env.APP_NAME }}-linux-${{ matrix.python-version }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10']
        architecture: ['x64']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyside6 python-socketio requests

    - name: Build macOS executable
      run: |
        python -m nuitka \
          --standalone \
          --onefile \
          --enable-plugin=pyside6 \
          --include-qt-plugins=all \
          --include-package=socketio \
          --include-package=engineio \
          --include-package=requests \
          --include-package=urllib3 \
          --include-package=charset_normalizer \
          --include-package=idna \
          --macos-target-arch=${{ matrix.architecture }} \
          --remove-output \
          --noinclude-pytest-mode=nofollow \
          --noinclude-unittest-mode=nofollow \
          --nofollow-imports \
          --follow-stdlib \
          --lto=yes \
          --jobs=4 \
          --output-filename=${{ env.APP_NAME }}-macos-${{ matrix.python-version }}-${{ matrix.architecture }} \
          app.py

          
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: ${{ env.APP_NAME }}-macos-${{ matrix.python-version }}-${{ matrix.architecture }}

  # 创建发布版本
  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/**/*